CREATE TABLE IF NOT EXISTS genres (
  genre_id integer PRIMARY KEY,
  name varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa (
  mpa_id integer PRIMARY KEY,
  name varchar(50) NOT NULL,
  description varchar(100)
);

CREATE TABLE IF NOT EXISTS films (
  film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  description varchar(200),
  release_date date,
  duration integer,
  mpa_id integer,
  CONSTRAINT fk_mpa_films FOREIGN KEY (mpa_id) REFERENCES mpa (mpa_id)
);

CREATE TABLE IF NOT EXISTS users (
  user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) NOT NULL,
  login varchar(255) NOT NULL,
  user_name varchar(255) NOT NULL,
  birthday date
);

CREATE TABLE IF NOT EXISTS film_genres (
  film_id integer,
  genre_id integer,
  PRIMARY KEY (film_id, genre_id),
  CONSTRAINT fk_film_film_genres FOREIGN KEY (film_id) REFERENCES films (film_id),
  CONSTRAINT fk_genre_film_genres FOREIGN KEY (genre_id) REFERENCES genres (genre_id)
);

CREATE TABLE IF NOT EXISTS friends (
  user_id integer,
  friend_id integer,
  PRIMARY KEY (user_id, friend_id),
  CONSTRAINT fk_user_friends FOREIGN KEY (user_id) REFERENCES users (user_id),
  CONSTRAINT fk_friend_friends FOREIGN KEY (friend_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS likes (
  film_id integer,
  user_id integer,
  PRIMARY KEY (film_id, user_id),
  CONSTRAINT fk_film_likes FOREIGN KEY (film_id) REFERENCES films (film_id),
  CONSTRAINT fk_user_likes FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS directors (
  director_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_directors (
  film_id integer,
  director_id integer,
  PRIMARY KEY (film_id, director_id),
  CONSTRAINT fk_film_film_directors FOREIGN KEY (film_id) REFERENCES films (film_id),
  CONSTRAINT fk_user_film_directors FOREIGN KEY (director_id) REFERENCES directors (director_id)
);

CREATE TABLE IF NOT EXISTS reviews (
  review_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content varchar(512) NOT NULL,
  is_positive bool NOT NULL,
  film_id integer NOT NULL,
  user_id integer NOT NULL,
  useful integer NOT NULL DEFAULT 0,
  CONSTRAINT fk_user_reviews FOREIGN KEY (user_id) REFERENCES users (user_id),
  CONSTRAINT fk_film_reviews FOREIGN KEY (film_id) REFERENCES films (film_id)
);

CREATE TABLE IF NOT EXISTS review_likes (
  review_id integer,
  user_id integer,
  is_like bool NOT NULL,
  PRIMARY KEY (review_id, user_id),
  CONSTRAINT fk_review_review_likes FOREIGN KEY (review_id) REFERENCES reviews (review_id),
  CONSTRAINT fk_user_review_likes FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS feed (
  event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  entity_id integer NOT NULL,
  timestamp timestamp NOT NULL,
  event_type varchar(10) NOT NULL,
  operation varchar(10) NOT NULL,
  CONSTRAINT fk_user_feed FOREIGN KEY (user_id) REFERENCES users (user_id)
);
